name: Build and Push to GHCR

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/solutiondd/front-satitcmu-admin

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create production env file
        shell: bash
        run: |
          cat <<EOF > .env
          VITE_APP_BASE_URL=${{ secrets.VITE_APP_BASE_URL }}
          VITE_IMG_PROFILE_URL=${{ secrets.VITE_IMG_PROFILE_URL }}
          EOF

      - name: Verify env file
        run: |
          ls -la
          cat .env

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:v1.0.${{ github.run_number }}
